// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oqlexample.proxies;

public enum Gender
{
	Male(new String[][] { new String[] { "en_US", "Male" } }),
	Female(new String[][] { new String[] { "en_US", "Female" } }),
	Other(new String[][] { new String[] { "en_US", "Other" } });

	private java.util.Map<String,String> captions;

	private Gender(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
