// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oqlexample.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class StringTemplateTest extends CustomJavaAction<java.lang.Void>
{
	private com.mendix.systemwideinterfaces.javaactions.parameters.IStringTemplate statement;

	public StringTemplateTest(IContext context, com.mendix.systemwideinterfaces.javaactions.parameters.IStringTemplate statement)
	{
		super(context);
		this.statement = statement;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringTemplateTest";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
