// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oql.proxies;

public enum ParameterType
{
	_Boolean(new String[][] { new String[] { "en_US", "Boolean" } }),
	String(new String[][] { new String[] { "en_US", "String" } }),
	DateTime(new String[][] { new String[] { "en_US", "DateTime" } }),
	Decimal(new String[][] { new String[] { "en_US", "Decimal" } }),
	Integer(new String[][] { new String[] { "en_US", "Integer" } }),
	_Long(new String[][] { new String[] { "en_US", "Long" } }),
	_Float(new String[][] { new String[] { "en_US", "Float" } });

	private java.util.Map<String,String> captions;

	private ParameterType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
