// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oqlexample.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the OQLExample module
	public static void aCT_GenerateOQLExport(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("OQLExample.ACT_GenerateOQLExport").withParams(params).execute(context);
	}
	public static void aCT_GenerateTestData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("OQLExample.ACT_GenerateTestData").withParams(params).execute(context);
	}
	public static void aCT_OpenOQLOverview(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("OQLExample.ACT_OpenOQLOverview").withParams(params).execute(context);
	}
	public static void stringTemplateTest(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("OQLExample.StringTemplateTest").withParams(params).execute(context);
	}
}
