// This file was generated by Mendix Modeler 6.9.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oqlexample.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the OQLExample module
	public static java.util.List<oqlexample.proxies.ExamplePersonResult> dS_ExampleOQL(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "OQLExample.DS_ExampleOQL", params);
			java.util.List<oqlexample.proxies.ExamplePersonResult> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<oqlexample.proxies.ExamplePersonResult>();
				for (IMendixObject obj : objs)
					result.add(oqlexample.proxies.ExamplePersonResult.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_CreateContent(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "OQLExample.IVK_CreateContent", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_PerformTests(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "OQLExample.IVK_PerformTests", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}