// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oqladdon.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the OQLAddOn module

	/**
	* When left empty, this will be the ID of the object. Else set your projects default here.
	*/
	public static java.lang.String getAddListParameterDefaultMember()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OQLAddOn.AddListParameterDefaultMember");
	}
}